const mksCurrentUser = {
  name: "Hasan Khan",
  roleLabel: "Project Manager",
  isAdmin: true
};
window.APP_CONFIG = {
  currentUser: mksCurrentUser,
  sidebarNav: [
    { key: "portfolio-home", label: "Home", icon: "grid", active: true },
    { key: "my-projects", label: "My projects", icon: "briefcase", active: false },
    { key: "roadmap", label: "Roadmap", icon: "roadmapchart", active: false },
    { key: "reports", label: "Reports", icon: "sheet", active: false },
    { key: "settings", label: "Settings", icon: "cog", active: false },
    { key: "help", label: "Help", icon: "help", active: false }
  ],
  intakeOptions: {
    strategicPillars: [
      "Sustainable success",
      "People first",
      "Clients at our core",
      "One firm philosophy",
      "Intelligent innovation"
    ],
    departments: ["IT", "Finance", "Facilities", "HR", "PMO", "MKS", "Tax", "Audit", "People", "Marketing", "L&D"],
    statuses: ["Draft", "Submitted", "Active", "On hold", "Completed"],
    budgetBands: [
      { value: "under15000", label: "Under GBP 15,000" },
      { value: "15000to25000", label: "GBP 15,000 to GBP 25,000" },
      { value: "25001to50000", label: "GBP 25,001 to GBP 50,000" },
      { value: "50001to70000", label: "GBP 50,001 to GBP 70,000" },
      { value: "70001to100000", label: "GBP 70,001 to GBP 100,000" },
      { value: "over100000", label: "Over GBP 100,000" }
    ],
    deliveryTimeline: [
      { value: "upto3", label: "Up to 3 months" },
      { value: "3to6", label: "3 to 6 months" },
      { value: "6to12", label: "6 to 12 months" },
      { value: "over12", label: "More than 12 months" }
    ],
    impactedTeams: [
      { value: "1", label: "1 team" },
      { value: "2to3", label: "2 to 3 teams" },
      { value: "4to5", label: "4 to 5 teams" },
      { value: "over5", label: "More than 5 teams" }
    ],
    audienceType: [
      { value: "internal", label: "Internal Only" },
      { value: "client", label: "Client Facing" },
      { value: "both", label: "Internal plus client" }
    ],
    strategicImportance: [
      { value: "low", label: "Low" },
      { value: "moderate", label: "Moderate" },
      { value: "high", label: "High" },
      { value: "critical", label: "Critical" }
    ]
  },
  documentTemplates: {
    "Project Charter": { file: "templates/Project Charter.docx", note: "Core initiation template for sponsor approval." },
    "Business Case": { file: "templates/Business Case template.docx", note: "Used for commercial and benefits justification." },
    "Risk Assessment Template": { file: "templates/Risk Assessment template.docx", note: "Required where delivery and operational risks must be recorded." },
    "Data Privacy Assessment Form": { file: "templates/Data Privacy Assessment form.docx", note: "Required when personal or client-sensitive data is involved." },
    "Information Security Review Form": { file: "templates/Information Security Review form.docx", note: "Required when security or technical controls must be assessed." }
  },
  mockProjects: [
    {
      id: 1,
      name: "1MKS Client Portal",
      status: "Submitted",
      tshirtSize: "S",
      completionPercentage: 0,
      projectManager: "Lazo Basic",
      primarySponsor: "Lazo Basic",
      department: "MKS",
      projectType: "Client portal",
      strategicPillar: "Clients at our core",
      budget: "GBP 50,001 to GBP 70,000",
      overallScore: 46,
      currentRisk: "Medium",
      roadmapPhase: "submitted",
      currentPhaseProgress: 0,
      timelineYear: 2026,
      timelineStartMonth: 5,
      timelineEndMonth: 10,
      whatHappenedLastMonth: "The 1MKS client portal proposal was submitted into the intake route and is waiting for the first decision board slot.",
      currentPosition: "Submitted, pending decision on the decision board before discovery or planning can begin.",
      next30DaysPipeline: "Take the submitted portal proposal through the decision board and confirm whether a six-month delivery window from May to October should be approved.",
      steeringDecisionNeeded: "Decision board approval is needed to confirm whether the 1MKS client portal proceeds as a six-month initiative from May to October.",
      businessObjective: "Create a client-facing 1MKS portal that gives a simpler and more joined-up digital entry point for clients.",
      projectHealthChartData: { governance: 2, sponsorEngagement: 2, scope: 3, budget: 3, schedule: 2, resourcing: 2, riskIssues: 3, quality: 3 },
      healthCheckReportUrl: ""
    },
    {
      id: 2,
      name: "iManage Cloud Phase 2",
      status: "Active",
      tshirtSize: "XL",
      completionPercentage: 62,
      projectManager: mksCurrentUser.name,
      primarySponsor: "Lazo Basic",
      department: "IT",
      projectType: "Technology implementation",
      strategicPillar: "Intelligent innovation",
      budget: "Over GBP 100,000",
      overallScore: 82,
      currentRisk: "Medium",
      roadmapPhase: "delivery",
      currentPhaseProgress: 62,
      timelineYear: 2026,
      timelineStartMonth: 1,
      timelineEndMonth: 9,
      whatHappenedLastMonth: "Wave one rollout settled well and the cloud cutover checklist was baselined for phase two delivery.",
      currentPosition: "Phase two delivery is underway with technical build, business readiness, and migration sequencing in flight.",
      next30DaysPipeline: "Complete the next migration wave, confirm cutover readiness, and close open integration actions.",
      steeringDecisionNeeded: "Confirm the final cutover date and support model for the next deployment wave.",
      businessObjective: "Move the legal and knowledge platform onto iManage Cloud with a stronger support and adoption model.",
      projectHealthChartData: { governance: 4, sponsorEngagement: 4, scope: 3, budget: 4, schedule: 3, resourcing: 3, riskIssues: 3, quality: 4 },
      healthCheckReportUrl: "reports/imanage-health-check.html"
    },
    {
      id: 3,
      name: "Project Flintstone - Legal PMS",
      status: "Active",
      tshirtSize: "L",
      completionPercentage: 18,
      projectManager: "To be confirmed",
      primarySponsor: "Kate Bowen",
      department: "IT",
      projectType: "Application change",
      strategicPillar: "Clients at our core",
      budget: "GBP 50,001 to GBP 70,000",
      overallScore: 58,
      currentRisk: "Medium",
      roadmapPhase: "discovery",
      currentPhaseProgress: 24,
      timelineYear: 2026,
      timelineStartMonth: 3,
      timelineEndMonth: 7,
      whatHappenedLastMonth: "The legal PMS opportunity was approved and discovery workshops started with legal operations and risk teams.",
      currentPosition: "The project is in discovery, working through current pain points, scope boundaries, and supplier assumptions.",
      next30DaysPipeline: "Finish discovery interviews, confirm the target operating model, and frame the outline business case.",
      steeringDecisionNeeded: "Confirm whether discovery should continue into full planning with the current supplier shortlist.",
      businessObjective: "Improve legal matter handling with a more resilient and better governed PMS process.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 4, scope: 3, budget: 3, schedule: 3, resourcing: 2, riskIssues: 3, quality: 4 },
      healthCheckReportUrl: ""
    },
    {
      id: 4,
      name: "CRM Optimisation",
      status: "Active",
      tshirtSize: "M",
      completionPercentage: 74,
      projectManager: "Lazo Basic",
      primarySponsor: "Dan Martin",
      department: "Marketing",
      projectType: "Business change",
      strategicPillar: "Clients at our core",
      budget: "GBP 25,001 to GBP 50,000",
      overallScore: 68,
      currentRisk: "Low",
      roadmapPhase: "delivery",
      currentPhaseProgress: 74,
      timelineYear: 2026,
      timelineStartMonth: 1,
      timelineEndMonth: 8,
      whatHappenedLastMonth: "Dashboard design was finalised and adoption actions were agreed with the campaign owners.",
      currentPosition: "The optimisation work is in delivery with reporting, data clean-up, and adoption tasks underway.",
      next30DaysPipeline: "Finish the reporting pack, complete user acceptance, and hand over the new process into BAU.",
      steeringDecisionNeeded: "Agree final ownership of the reporting backlog and the post-launch KPI set.",
      businessObjective: "Improve client touchpoints and reporting through a cleaner and more usable CRM operating model.",
      projectHealthChartData: { governance: 4, sponsorEngagement: 4, scope: 4, budget: 4, schedule: 4, resourcing: 3, riskIssues: 4, quality: 4 },
      healthCheckReportUrl: "reports/crm-health-check.html"
    },
    {
      id: 5,
      name: "The MKS Way",
      status: "Planning",
      tshirtSize: "L",
      completionPercentage: 34,
      projectManager: "Ross Andrean",
      primarySponsor: "Dan Martin",
      department: "PMO",
      projectType: "Operating model",
      strategicPillar: "Sustainable success",
      budget: "GBP 50,001 to GBP 70,000",
      overallScore: 61,
      currentRisk: "Medium",
      roadmapPhase: "definition",
      currentPhaseProgress: 44,
      timelineYear: 2026,
      timelineStartMonth: 9,
      timelineEndMonth: 12,
      whatHappenedLastMonth: "The design direction for The MKS Way was agreed and the planning work started with the PMO and app delivery team.",
      currentPosition: "In planning and design, with the PMO workflow, app experience, and implementation scope being shaped together.",
      next30DaysPipeline: "Complete the planning baseline, confirm the design approach, and move the app build into its first controlled sprint.",
      steeringDecisionNeeded: "Approve the pilot scope and the central support model before delivery begins.",
      businessObjective: "Create one joined-up PMO intake, governance, and reporting experience across the firm.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 3, scope: 4, budget: 3, schedule: 3, resourcing: 2, riskIssues: 3, quality: 3 },
      healthCheckReportUrl: ""
    },
    {
      id: 6,
      name: "HR System Upgrade",
      status: "Active",
      tshirtSize: "M",
      completionPercentage: 22,
      projectManager: "To be confirmed",
      primarySponsor: "Victoria Ponda",
      department: "HR",
      projectType: "Platform upgrade",
      strategicPillar: "People first",
      budget: "GBP 25,001 to GBP 50,000",
      overallScore: 54,
      currentRisk: "Medium",
      roadmapPhase: "discovery",
      currentPhaseProgress: 30,
      timelineYear: 2026,
      timelineStartMonth: 2,
      timelineEndMonth: 8,
      whatHappenedLastMonth: "The HR platform review was approved into discovery and stakeholder interviews started across people operations and payroll.",
      currentPosition: "The project is in discovery, working through process pain points, platform constraints, and future-state requirements.",
      next30DaysPipeline: "Finish discovery workshops, confirm the scope boundary, and prepare the planning recommendation for HR leadership.",
      steeringDecisionNeeded: "Agree whether the discovery output is sufficient to move the HR system upgrade into formal planning.",
      businessObjective: "Refresh the HR platform approach so core employee lifecycle processes are more resilient and easier to manage.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 4, scope: 3, budget: 3, schedule: 3, resourcing: 3, riskIssues: 3, quality: 4 },
      healthCheckReportUrl: "reports/hr-upgrade-health-check.html"
    },
    {
      id: 7,
      name: "Nuthatch",
      status: "Submitted",
      tshirtSize: "M",
      completionPercentage: 0,
      projectManager: "To be confirmed",
      primarySponsor: "David Painter",
      department: "Finance",
      projectType: "Client-facing initiative",
      strategicPillar: "One firm philosophy",
      budget: "Under GBP 15,000",
      overallScore: 53,
      currentRisk: "Submitted - pending review",
      roadmapPhase: "submitted",
      currentPhaseProgress: 0,
      timelineYear: 2026,
      timelineStartMonth: 4,
      timelineEndMonth: 9,
      whatHappenedLastMonth: "The project brief and supporting documents were submitted into the intake workflow.",
      currentPosition: "Submitted and waiting for PMO and Finance leadership review before the next decision board.",
      next30DaysPipeline: "Complete the PMO and department review, confirm whether any clarifications are needed, and take the proposal to the next decision board.",
      steeringDecisionNeeded: "A decision board outcome is needed to confirm whether the project is approved to move forward or sent back for more detail.",
      businessObjective: "This is an MnA project to integrate CMIS and Augustine to MKS Financial",
      projectHealthChartData: { governance: 2, sponsorEngagement: 2, scope: 3, budget: 3, schedule: 2, resourcing: 2, riskIssues: 3, quality: 3 },
      healthCheckReportUrl: ""
    },
    {
      id: 8,
      name: "PracticePoint",
      status: "Active",
      tshirtSize: "M",
      completionPercentage: 16,
      projectManager: "Ross Andrean",
      primarySponsor: "Lazo Basic",
      department: "IT",
      projectType: "Knowledge and workflow review",
      strategicPillar: "Clients at our core",
      budget: "GBP 25,001 to GBP 50,000",
      overallScore: 55,
      currentRisk: "Medium",
      roadmapPhase: "discovery",
      currentPhaseProgress: 28,
      timelineYear: 2026,
      timelineStartMonth: 4,
      timelineEndMonth: 9,
      whatHappenedLastMonth: "PracticePoint was approved into discovery and the first current-state process walkthroughs were completed.",
      currentPosition: "The project is in discovery, looking at workflow pain points, controls, and user adoption barriers.",
      next30DaysPipeline: "Complete discovery interviews, confirm scope options, and prepare the planning recommendation.",
      steeringDecisionNeeded: "Confirm whether PracticePoint should progress into detailed planning after discovery closes.",
      businessObjective: "Improve practice workflow consistency and visibility through a better governed PracticePoint process.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 3, scope: 3, budget: 3, schedule: 3, resourcing: 2, riskIssues: 3, quality: 3 },
      healthCheckReportUrl: ""
    },
    {
      id: 9,
      name: "Refurb 12 Appold Street",
      status: "Planning",
      tshirtSize: "L",
      completionPercentage: 18,
      projectManager: "Simon Booth",
      primarySponsor: "Dan Martin",
      department: "Facilities",
      projectType: "Office refurbishment",
      strategicPillar: "Sustainable success",
      budget: "GBP 70,001 to GBP 100,000",
      overallScore: 59,
      currentRisk: "Medium",
      roadmapPhase: "definition",
      currentPhaseProgress: 22,
      timelineYear: 2026,
      timelineStartMonth: 7,
      timelineEndMonth: 12,
      whatHappenedLastMonth: "The building brief was approved and the first planning conversations started with facilities, IT, and workplace stakeholders.",
      currentPosition: "Approved and in planning, with the early design, move assumptions, and supplier route being shaped.",
      next30DaysPipeline: "Confirm the refurbishment scope, planning assumptions, and the phased delivery approach for 12 Appold Street.",
      steeringDecisionNeeded: "Approve the planning baseline and preferred delivery route before detailed design is commissioned.",
      businessObjective: "Refurbish 12 Appold Street so the space better supports teams, clients, and hybrid ways of working.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 3, scope: 4, budget: 3, schedule: 3, resourcing: 2, riskIssues: 3, quality: 3 },
      healthCheckReportUrl: ""
    }
  ]
};

