window.APP_CONFIG = {
  sidebarNav: [
    { key: "portfolio-home", label: "Portfolio home", icon: "grid", active: true },
    { key: "my-projects", label: "My projects", icon: "briefcase", active: false },
    { key: "roadmap", label: "Roadmap", icon: "route", active: false },
    { key: "reports", label: "Reports", icon: "chart", active: false },
    { key: "settings", label: "Settings", icon: "cog", active: false }
  ],
  intakeOptions: {
    strategicPillars: [
      "Sustainable success",
      "People first",
      "Clients at our core",
      "One firm philosophy",
      "Intelligent innovation"
    ],
    departments: ["IT", "Finance", "Facilities", "HR", "Tax", "Audit", "People", "Marketing", "L&D"],
    statuses: ["Draft", "Submitted", "Active", "On hold", "Completed"],
    budgetBands: [
      { value: "under15000", label: "Under GBP 15,000" },
      { value: "15000to25000", label: "GBP 15,000 to GBP 25,000" },
      { value: "25001to50000", label: "GBP 25,001 to GBP 50,000" },
      { value: "50001to70000", label: "GBP 50,001 to GBP 70,000" },
      { value: "70001to100000", label: "GBP 70,001 to GBP 100,000" },
      { value: "over100000", label: "Over GBP 100,000" }
    ],
    deliveryTimeline: [
      { value: "upto3", label: "Up to 3 months" },
      { value: "3to6", label: "3 to 6 months" },
      { value: "6to12", label: "6 to 12 months" },
      { value: "over12", label: "More than 12 months" }
    ],
    impactedTeams: [
      { value: "1", label: "1 team" },
      { value: "2to3", label: "2 to 3 teams" },
      { value: "4to5", label: "4 to 5 teams" },
      { value: "over5", label: "More than 5 teams" }
    ],
    audienceType: [
      { value: "internal", label: "Internal Only" },
      { value: "client", label: "Client Facing" }
    ],
    strategicImportance: [
      { value: "low", label: "Low" },
      { value: "moderate", label: "Moderate" },
      { value: "high", label: "High" },
      { value: "critical", label: "Critical" }
    ]
  },
  documentTemplates: {
    "Project Charter": { file: "templates/Project Charter.docx", note: "Core initiation template for sponsor approval." },
    "Business Case": { file: "templates/Business Case template.docx", note: "Used for commercial and benefits justification." },
    "Risk Assessment Template": { file: "templates/Risk Assessment template.docx", note: "Required where delivery and operational risks must be recorded." },
    "Data Privacy Assessment Form": { file: "templates/Data Privacy Assessment form.docx", note: "Required when personal or client-sensitive data is involved." },
    "Information Security Review Form": { file: "templates/Information Security Review form.docx", note: "Required when security or technical controls must be assessed." }
  },
  mockProjects: [
    {
      id: 1,
      name: "OneMKS",
      status: "Draft",
      tshirtSize: "S",
      completionPercentage: 0,
      projectManager: "Lazo Basic",
      primarySponsor: "Dan Martine",
      department: "Audit",
      projectType: "Internal transformation",
      strategicPillar: "One firm philosophy",
      budget: "GBP 25,001 to GBP 50,000",
      overallScore: 40,
      currentRisk: "Low",
      whatHappenedLastMonth: "Initial discovery workshops completed and the intake requirements were drafted.",
      currentPosition: "Awaiting sponsor review of the project charter and early governance pack.",
      next30DaysPipeline: "Confirm governance route and finalise the first-cut delivery plan.",
      steeringDecisionNeeded: "Agree whether the pilot should run with one business area or across the full firm.",
      businessObjective: "Create a unified operating model for project intake across the firm.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 4, scope: 3, budget: 3, schedule: 3, resourcing: 2, riskIssues: 3, quality: 4 },
      healthCheckReportUrl: ""
    },
    {
      id: 2,
      name: "iManage",
      status: "Active",
      tshirtSize: "XL",
      completionPercentage: 65,
      projectManager: "Hasan Khan",
      primarySponsor: "Lazo Basic",
      department: "IT",
      projectType: "Technology implementation",
      strategicPillar: "Intelligent innovation",
      budget: "Over GBP 100,000",
      overallScore: 82,
      currentRisk: "Medium",
      whatHappenedLastMonth: "Migration pilot completed with strong adoption across the initial legal cohort.",
      currentPosition: "Wave two rollout activities are underway and business readiness is progressing.",
      next30DaysPipeline: "Complete training, finish integrations, and confirm the next migration wave.",
      steeringDecisionNeeded: "Approve the final migration window and business support model for full rollout.",
      businessObjective: "Modernise document and knowledge workflows for client delivery teams.",
      projectHealthChartData: { governance: 4, sponsorEngagement: 4, scope: 3, budget: 4, schedule: 3, resourcing: 3, riskIssues: 3, quality: 4 },
      healthCheckReportUrl: "reports/imanage-health-check.html"
    },
    {
      id: 3,
      name: "Project Flintstone - Legal PMS",
      status: "Active",
      tshirtSize: "L",
      completionPercentage: 40,
      projectManager: "Hasan Khan",
      primarySponsor: "Lazo Basic",
      department: "IT",
      projectType: "Application change",
      strategicPillar: "Clients at our core",
      budget: "GBP 50,001 to GBP 70,000",
      overallScore: 63,
      currentRisk: "Medium",
      whatHappenedLastMonth: "Supplier workshops finished and the target operating model was reviewed with legal stakeholders.",
      currentPosition: "Requirements and core design decisions have been agreed but supplier dates remain under review.",
      next30DaysPipeline: "Begin configuration sprint, controls review, and early test planning.",
      steeringDecisionNeeded: "Confirm whether the first release should proceed with a phased or single-cutover approach.",
      businessObjective: "Improve legal matter handling with a more resilient PMS process.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 4, scope: 4, budget: 3, schedule: 2, resourcing: 3, riskIssues: 2, quality: 4 },
      healthCheckReportUrl: ""
    },
    {
      id: 4,
      name: "CRM Optimisation",
      status: "Active",
      tshirtSize: "M",
      completionPercentage: 80,
      projectManager: "Hasan Khan",
      primarySponsor: "Lazo Basic",
      department: "Marketing",
      projectType: "Business change",
      strategicPillar: "Clients at our core",
      budget: "GBP 25,001 to GBP 50,000",
      overallScore: 51,
      currentRisk: "Low",
      whatHappenedLastMonth: "Process redesign completed and campaign owners were trained on the new CRM flow.",
      currentPosition: "The final sprint is focused on dashboards, cleanup, and release readiness.",
      next30DaysPipeline: "Deploy new reporting and close outstanding BAU handover tasks.",
      steeringDecisionNeeded: "Agree success metrics for post-launch adoption and ownership of the reporting backlog.",
      businessObjective: "Improve client touchpoints and reporting through a cleaner CRM operating model.",
      projectHealthChartData: { governance: 4, sponsorEngagement: 4, scope: 4, budget: 4, schedule: 4, resourcing: 3, riskIssues: 4, quality: 4 },
      healthCheckReportUrl: "reports/crm-health-check.html"
    },
    {
      id: 5,
      name: "myMKSWay PMO build",
      status: "Planning",
      tshirtSize: "L",
      completionPercentage: 15,
      projectManager: "Hasan Khan",
      primarySponsor: "Lazo Basic",
      department: "People",
      projectType: "Operating model",
      strategicPillar: "Sustainable success",
      budget: "GBP 50,001 to GBP 70,000",
      overallScore: 57,
      currentRisk: "Medium",
      whatHappenedLastMonth: "The initial design concepts were approved and the minimum viable process was agreed.",
      currentPosition: "Defining the data model, governance workflow, and implementation plan.",
      next30DaysPipeline: "Finish the MVP design and confirm the pilot group and rollout approach.",
      steeringDecisionNeeded: "Approve the pilot scope and the level of PMO central support for launch.",
      businessObjective: "Create a single PMO intake and governance experience across the firm.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 3, scope: 4, budget: 3, schedule: 3, resourcing: 2, riskIssues: 3, quality: 3 },
      healthCheckReportUrl: ""
    },
    {
      id: 6,
      name: "HR System Upgrade",
      status: "Completed",
      tshirtSize: "S",
      completionPercentage: 100,
      projectManager: "Robin Taylor",
      primarySponsor: "Sarah Kent",
      department: "HR",
      projectType: "Platform upgrade",
      strategicPillar: "People first",
      budget: "GBP 15,000 to GBP 25,000",
      overallScore: 38,
      currentRisk: "Low",
      whatHappenedLastMonth: "Post-go-live actions were completed and the service was fully handed over to BAU support.",
      currentPosition: "Project closed with all actions and benefits tracking signed off.",
      next30DaysPipeline: "Only post-implementation review and benefits capture remain.",
      steeringDecisionNeeded: "No steering decision needed; closed project.",
      businessObjective: "Refresh the HR platform to improve core employee lifecycle processes.",
      projectHealthChartData: { governance: 5, sponsorEngagement: 4, scope: 5, budget: 5, schedule: 5, resourcing: 4, riskIssues: 5, quality: 5 },
      healthCheckReportUrl: "reports/hr-upgrade-health-check.html"
    },
    {
      id: 7,
      name: "Finance Reporting v2",
      status: "On hold",
      tshirtSize: "M",
      completionPercentage: 30,
      projectManager: "Sam Lowe",
      primarySponsor: "Mark Davies",
      department: "Finance",
      projectType: "Reporting transformation",
      strategicPillar: "Sustainable success",
      budget: "GBP 25,001 to GBP 50,000",
      overallScore: 48,
      currentRisk: "Medium",
      whatHappenedLastMonth: "Dependencies on data remediation delayed the current reporting release.",
      currentPosition: "Project paused while source system quality issues are being worked through.",
      next30DaysPipeline: "Re-baseline the roadmap once the data engineering fixes are confirmed.",
      steeringDecisionNeeded: "Decide whether to continue with the original scope or reduce the first release to a smaller MVP.",
      businessObjective: "Improve management reporting accuracy and reduce month-end effort.",
      projectHealthChartData: { governance: 3, sponsorEngagement: 3, scope: 3, budget: 3, schedule: 2, resourcing: 2, riskIssues: 2, quality: 3 },
      healthCheckReportUrl: ""
    }
  ]
};
